### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ncarrara** [eleurent/who-s-on-my-gpu#2]
File "who_s_on_my_gpu.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

  File "who_s_on_my_gpu.py", line 8, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'

Traceback (most recent call last):
  File "who_s_on_my_gpu.py", line 10, in <module>
    import tabulate
ModuleNotFoundError: No module named 'tabulate'

**Comment by xuedong** [comment]
bah, tu les installes toi-même ok ?

**Comment by ncarrara** [comment]
Must be self contained you noob
